### ISSUE TITLE
Error when expanding local variable with Flutter Web

### ISSUE THREAD

**Issue by Pacane** [emacs-lsp/lsp-dart#187]
**Describe the bug**
When expanding a local variable (not happening with all variables), in the DAP ui mode, I get an exception.

For reference, I tried expanding the variable `searchState` in my case.

**To Reproduce**
I'm using a closed source project, but what I'm doing specifically is trying to expand a variable that's passed as a closure, which has for type a Freezed union type value.

**Expected behavior**
It would expand the thing normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/2762440/205930771-4a410297-9cfc-4363-91d2-ea628a083f9d.png)

**Version**
Include here the result of: <kbd>M-x</kbd> `lsp-dart-version`
![image](https://user-images.githubusercontent.com/2762440/205930890-2e5336fd-ecc0-4974-96bf-521a7156ef9f.png)

Here's the actual stacktrace

```
LSP :: Connected to [dart_analysis_server:2563275].
dap-request: getObject: (-32603) getObject: Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: TypeError: Cannot read properties of undefined (reading ’name’)
    at <anonymous>:9:25
    at <anonymous>:83:7
    at http://localhost:37141/packages/braver_flutter_domain_ui/src/pages/profile/sections/visibility/select_professions_search_capsule.dart.lib.js:155:15
    at Generator.next (<anonymous>)
    at runBody (http://localhost:37141/dart_sdk.js:40595:34)
    at Object._async [as async] (http://localhost:37141/dart_sdk.js:40626:7)
    at SearchCapsule.new.<anonymous> (http://localhost:37141/packages/braver_flutter_domain_ui/src/pages/profile/sections/visibility/select_professions_search_capsule.dart.lib.js:154:674)
    at SearchCapsule.new.triggerBuilder (http://localhost:37141/packages/braver_flutter_ui/src/themed_app.dart.lib.js:15279:74)
    at triggerBuilder.next (<anonymous>)
    at runBody (http://localhost:37141/dart_sdk.js:40595:34)
    at Object._async [as async] (http://localhost:37141/dart_sdk.js:40626:7)
    at SearchCapsule.new.triggerBuilder (http://localhost:37141/packages/braver_flutter_ui/src/themed_app.dart.lib.js:15277:22)
    at _MapStream.new.<anonymous> (http://localhost:37141/packages/braver_flutter_ui/src/themed_app.dart.lib.js:15144:286)
    at [_handleData] (http://localhost:37141/dart_sdk.js:38392:60)
    at [_handleData] (http://localhost:37141/dart_sdk.js:38300:37)
    at _rootRunUnary (http://localhost:37141/dart_sdk.js:40864:46)
    at async._CustomZone.new.runUnary (http://localhost:37141/dart_sdk.js:40047:14)
    at async._CustomZone.new.runUnaryGuarded (http://localhost:37141/dart_sdk.js:39967:14)
    at [_sendData] (http://localhost:37141/dart_sdk.js:34170:22)
    at _DelayedData.new.perform (http://localhost:37141/dart_sdk.js:37455:28)
    at _PendingEvents.new.handleNext (http://localhost:37141/dart_sdk.js:37592:15)
    at http://localhost:37141/dart_sdk.js:37564:16
    at _rootRun (http://localhost:37141/dart_sdk.js:40852:46)
    at async._CustomZone.new.run (http://localhost:37141/dart_sdk.js:40041:14)
    at async._CustomZone.new.runGuarded (http://localhost:37141/dart_sdk.js:39955:14)
    at http://localhost:37141/dart_sdk.js:40003:33
    at _rootRun (http://localhost:37141/dart_sdk.js:40858:14)
    at async._CustomZone.new.run (http://localhost:37141/dart_sdk.js:40041:14)
    at async._CustomZone.new.runGuarded (http://localhost:37141/dart_sdk.js:39955:14)
    at async._AsyncCallbackEntry.new.callback (http://localhost:37141/dart_sdk.js:40003:33)
    at Object._microtaskLoop (http://localhost:37141/dart_sdk.js:40705:13)
    at _startMicrotaskLoop (http://localhost:37141/dart_sdk.js:40711:13)
    at http://localhost:37141/dart_sdk.js:36447:9
  type: object
  value: null
attempted JS eval: ‘    (function() {
         var sdkUtils = require(’dart_sdk’).dart;
   var library = sdkUtils.getLibrary(’package:braver_flutter_ui/src/components/forms/search_capsule.dart’);
   if (!library) throw ’cannot find library for package:braver_flutter_ui/src/components/forms/search_capsule.dart’;
  
      var result = {};
      var clazz = library["_$36_Closed"];
      var descriptor = {
          ’name’: clazz.name,
          ’dartName’: sdkUtils.typeName(clazz)
        };

      // TODO(grouma) - we display all inherited methods since we don’t provide
      // the superClass information. This is technically not correct.
      var proto = clazz.prototype;
      var methodNames = [];
      for (; proto != null; proto = Object.getPrototypeOf(proto)) {
        var methods = Object.getOwnPropertyNames(proto);
        for (var i = 0; i < methods.length; i++) {
          if (methodNames.indexOf(methods[i]) == -1
              && methods[i] != ’constructor’) {
              methodNames.push(methods[i]);
          }
        }
        if (proto.constructor.name == ’Object’) break;
      }

      descriptor[’methods’] = {};
      for (var name of methodNames) {
        descriptor[’methods’][name] = {
          // TODO(jakemac): how can we get actual const info?
          "isConst": false,
          "isStatic": false,
        }
      }

      var fields = sdkUtils.getFields(clazz);
      var fieldNames = fields ? Object.keys(fields) : [];
      descriptor[’fields’] = {};
      for (var name of fieldNames) {
        var field = fields[name];
        var libraryUri = Object.getOwnPropertySymbols(fields[name]["type"])
        .find(x => x.description == "libraryUri");
        descriptor[’fields’][name] = {
          // TODO(jakemac): how can we get actual const info?
          "isConst": false,
          "isFinal": field.isFinal,
          "isStatic": false,
          "classRefName": fields[name]["type"]["name"],
          "classRefDartName": sdkUtils.typeName(fields[name]["type"]),
          "classRefLibraryId" : field["type"][libraryUri],
        }
      }

      // TODO(elliette): The following static member information is minimal and 
      // should be replaced once DDC provides full symbol information (see 
      // https://github.com/dart-lang/sdk/issues/40273):

      descriptor[’staticFields’] = {};
      var staticFieldNames = sdkUtils.getStaticFields(clazz) ?? [];
      for (const name of staticFieldNames) {
        descriptor[’staticFields’][name] = {
          "isStatic": true,
          // DDC only provides names of static members, we set isConst/isFinal 
          // to false even though they could be true.
          "isConst": false,
          "isFinal": false,
        }
      }

      descriptor[’staticMethods’] = {};
      var staticMethodNames = sdkUtils.getStaticMethods(clazz) ?? [];
      for (var name of staticMethodNames) {
        descriptor[’methods’][name] = {
          // DDC only provides names of static members, we set isConst
          // to false even though it could be true.
          "isConst": false,
          "isStatic": true,
        } 
      }

      return descriptor;
    })()
    ‘

#0      ClassHelper._constructClass (package:dwds/src/debugging/classes.dart:178:7)
<asynchronous suspension>
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>
```

**Comment by Pacane** [comment]
Just to be clear, I haven't personally tried on VSCode, but I have asked colleagues if it worked. I could try to install VSCode myself and try it (I'm not using it normally, I'm using IntelliJ mostly)
