### ISSUE TITLE
LSP Dart Server dies when I open a Dart file

### ISSUE THREAD

**Issue by renatoathaydes** [emacs-lsp/lsp-dart#191]
**Describe the bug**

When I edit [this particular file](https://github.com/renatoathaydes/dartle/blob/663f3e9d5b7c7be8e8865534fee66915f6ff0de3/lib/src/task.dart) on emacs, the LSP Dart Server dies, repeatedly.

The changes I was making are included below.

The server logged this to stderr:

```
Unhandled exception:
type 'GenericFunctionTypeImpl' is not a subtype of type 'NamedType' in type cast
#0      AstBuilder.popTypedList2 (package:analyzer/src/fasta/ast_builder.dart:4181:37)
#1      AstBuilder.handleMixinOn (package:analyzer/src/fasta/ast_builder.dart:3637:19)
#2      Parser.parseMixinOn (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2571:14)
#3      Parser.parseMixinOnOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2556:12)
#4      Parser.parseMixinHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2468:13)
#5      Parser.parseMixin (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2455:19)
#6      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:609:18)
#7      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:497:14)
#8      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#9      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:108:32)
#10     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:104:12)
#11     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:788:23)
#12     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:563:14)
#13     FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:734:16)
#14     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:600:27)
#15     FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:162:29)
#16     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#17     FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:157:20)
#18     FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:232:9)
#19     AnalysisDriver._applyPendingFileChanges (package:analyzer/src/dart/analysis/driver.dart:1252:25)
#20     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2060:18)
<asynchronous suspension>


#0      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:565:7)
#1      FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:734:16)
#2      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:600:27)
#3      FileTracker.verifyApiSignature.<anonymous closure> (package:analyzer/src/dart/analysis/file_tracker.dart:162:29)
#4      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#5      FileTracker.verifyApiSignature (package:analyzer/src/dart/analysis/file_tracker.dart:157:20)
#6      FileTracker.verifyChangedFilesIfNeeded (package:analyzer/src/dart/analysis/file_tracker.dart:232:9)
#7      AnalysisDriver._applyPendingFileChanges (package:analyzer/src/dart/analysis/driver.dart:1252:25)
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2060:18)
<asynchronous suspension>

Process dart_analysis_server stderr finished
Unhandled exception:
type 'GenericFunctionTypeImpl' is not a subtype of type 'NamedType' in type cast
#0      AstBuilder.popTypedList2 (package:analyzer/src/fasta/ast_builder.dart:4181:37)
#1      AstBuilder.handleMixinOn (package:analyzer/src/fasta/ast_builder.dart:3637:19)
#2      Parser.parseMixinOn (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2571:14)
#3      Parser.parseMixinOnOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2556:12)
#4      Parser.parseMixinHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2468:13)
#5      Parser.parseMixin (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2455:19)
#6      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:609:18)
#7      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:497:14)
#8      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#9      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:108:32)
#10     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:104:12)
#11     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:788:23)
#12     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:563:14)
#13     FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:734:16)
#14     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:600:27)
#15     FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1502:10)
#16     FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1334:14)
#17     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1318:12)
#18     AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1533:16)
#19     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1024:5)
#20     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2105:24)
<asynchronous suspension>


#0      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:565:7)
#1      FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:734:16)
#2      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:600:27)
#3      FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1502:10)
#4      FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1334:14)
#5      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1318:12)
#6      AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1533:16)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1024:5)
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2105:24)
<asynchronous suspension>

Process dart_analysis_server stderr finished
Unhandled exception:
type 'GenericFunctionTypeImpl' is not a subtype of type 'NamedType' in type cast
#0      AstBuilder.popTypedList2 (package:analyzer/src/fasta/ast_builder.dart:4181:37)
#1      AstBuilder.handleMixinOn (package:analyzer/src/fasta/ast_builder.dart:3637:19)
#2      Parser.parseMixinOn (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2571:14)
#3      Parser.parseMixinOnOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2556:12)
#4      Parser.parseMixinHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2468:13)
#5      Parser.parseMixin (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2455:19)
#6      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:609:18)
#7      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:497:14)
#8      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#9      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:108:32)
#10     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:104:12)
#11     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:788:23)
#12     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:563:14)
#13     FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:734:16)
#14     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:600:27)
#15     FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1502:10)
#16     FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1334:14)
#17     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1318:12)
#18     AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1533:16)
#19     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1024:5)
#20     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2105:24)
<asynchronous suspension>


#0      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:565:7)
#1      FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:734:16)
#2      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:600:27)
#3      FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1502:10)
#4      FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1334:14)
#5      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1318:12)
#6      AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1533:16)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1024:5)
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2105:24)
<asynchronous suspension>

Process dart_analysis_server stderr finished
Unhandled exception:
type 'GenericFunctionTypeImpl' is not a subtype of type 'NamedType' in type cast
#0      AstBuilder.popTypedList2 (package:analyzer/src/fasta/ast_builder.dart:4181:37)
#1      AstBuilder.handleMixinOn (package:analyzer/src/fasta/ast_builder.dart:3637:19)
#2      Parser.parseMixinOn (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2571:14)
#3      Parser.parseMixinOnOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2556:12)
#4      Parser.parseMixinHeaderOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2468:13)
#5      Parser.parseMixin (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2455:19)
#6      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:609:18)
#7      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:497:14)
#8      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#9      Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:108:32)
#10     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:104:12)
#11     FileState._parse (package:analyzer/src/dart/analysis/file_state.dart:788:23)
#12     FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:563:14)
#13     FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:734:16)
#14     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:600:27)
#15     FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1502:10)
#16     FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1334:14)
#17     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1318:12)
#18     AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1533:16)
#19     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1024:5)
#20     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2105:24)
<asynchronous suspension>


#0      FileState.parse (package:analyzer/src/dart/analysis/file_state.dart:565:7)
#1      FileState._getUnlinkedUnit (package:analyzer/src/dart/analysis/file_state.dart:734:16)
#2      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:600:27)
#3      FileSystemState._newFile (package:analyzer/src/dart/analysis/file_state.dart:1502:10)
#4      FileSystemState.getFileForPath2 (package:analyzer/src/dart/analysis/file_state.dart:1334:14)
#5      FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:1318:12)
#6      AnalysisDriver._discoverLibraries (package:analyzer/src/dart/analysis/driver.dart:1533:16)
#7      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1024:5)
#8      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2105:24)
<asynchronous suspension>

Process dart_analysis_server stderr finished

```

LDP Dart Version:

```
lsp-dart                       20221226.1829  available    melpa    Dart support lsp-mode
```

**To Reproduce**

Here's the changes I was making to the file:

```
modified   lib/src/task.dart
@@ -1,6 +1,7 @@
 import 'dart:async';
 
 import 'package:collection/collection.dart';
+import 'package:dartle/dartle_cache.dart';
 
 import '_utils.dart';
 import 'error.dart';
@@ -170,6 +171,12 @@ extension TaskPhaseString on TaskPhase {
   String name() => toString().substring('TaskPhase.'.length);
 }
 
+/// A mixin that can be used by a [Task] action in order to receive
+mixin IncrementalAction on Function(List<String>) {
+  /// Receive the detected changes before running.
+  void set changes(List<FileChange> changes);
+}
+
```

**Expected behavior**

LSP Dart continues helping me a lot.

**Version**

> I've just upgraded to latest, tried again, same result.

```
[LSP Dart] 1.24.1 at 2023.01.12 @ Emacs 28.1
[Dart SDK] Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "macos_x64"

[Flutter SDK] Not found
[Flutter project] false
[Project entrypoint] Not found
```

**Comment by renatoathaydes** [comment]
Looks like this is a Dart Analyser issue:

https://github.com/emacs-lsp/lsp-dart/issues/191

I will close this, sorry!
